[pytest]
addopts = -ra -q --html=reports/report.html --self-contained-html --alluredir=allure-results --reruns 1 --reruns-delay 1
python_files = test_*.py
testpaths = tests
markers =
    smoke: quick smoke tests
    regression: regression tests
    api: api validation tests
    ui: ui validation tests
    critical: critical path tests
filterwarnings = ignore::DeprecationWarning
xfail_strict = true
